steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'build', '--builder', 'default', '--platform', 'linux/amd64', '-t', 'us-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'build','--push','-t', 'us-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$SHORT_SHA']
- name: 'gcr.io/google-cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '$SERVICE_NAME'
    - '--image'
    - 'us-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$SHORT_SHA'
    - '--region=$REGION' # Replace with your region
  # Add any other Cloud Run deployment flags here